export enum EnvironmentKey {
  API_PORT = 'API_PORT',
  API_SECRET = 'API_SECRET',
  DB_HOST = 'DB_HOST',
  DB_NAME = 'DB_NAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  JWT_ACCESS_TOKEN_EXPIRATION = 'JWT_ACCESS_TOKEN_EXPIRATION',
  JWT_REFRESH_TOKEN_EXPIRATION = 'JWT_REFRESH_TOKEN_EXPIRATION',
}
